apiVersion: v1
kind: Pod
spec:
  containers:
  - name: cdt
    image: quay.io/eclipse-cdt/cdt-infra-plus-eclipse-install@sha256:e094fade3865aa5118b586a4e10c8bdf86e674c7075ffe5efd30ec38183c358e
    tty: true
    args: ["/bin/sh", "-c", "/home/vnc/.vnc/xstartup.sh && cat"]
    resources:
      requests:
        memory: "2662Mi"
        cpu: "1"
      limits:
        memory: "2662Mi"
        cpu: "1"
    volumeMounts:
    - name: settings-xml
      mountPath: /home/jenkins/.m2/settings.xml
      subPath: settings.xml
      readOnly: true
    - name: m2-repo
      mountPath: /home/jenkins/.m2/repository
  volumes:
  - name: settings-xml
    secret:
      secretName: m2-secret-dir
      items:
      - key: settings.xml
        path: settings.xml
  - name: m2-repo
    emptyDir: {}
