apiVersion: v1
kind: Pod
spec:
  containers:
  - name: cdt
    image: quay.io/eclipse-cdt/cdt-infra-eclipse-full@sha256:361c1ba81205d8ffa6793d21ef60bb3d0b1f9f24b427c36192d3e5be645469df
    tty: true
    args: ["/bin/sh", "-c", "/home/vnc/.vnc/xstartup.sh && cat"]
    resources:
      requests:
        memory: "2662Mi"
        cpu: "1"
      limits:
        memory: "2662Mi"
        cpu: "1"
    volumeMounts:
    - name: settings-xml
      mountPath: /home/jenkins/.m2/settings.xml
      subPath: settings.xml
      readOnly: true
    - name: m2-repo
      mountPath: /home/jenkins/.m2/repository
  volumes:
  - name: settings-xml
    secret:
      secretName: m2-secret-dir
      items:
      - key: settings.xml
        path: settings.xml
  - name: m2-repo
    emptyDir: {}
