apiVersion: v1
kind: Pod
spec:
  containers:
  - name: cdt
    image: quay.io/eclipse-cdt/cdt-infra-eclipse-full@sha256:8be256daaafbc46ffc28ab672bd73250611372980a9096546df423a462a162b1
    tty: true
    command: ["/bin/sh"]
    args: ["-c", "/home/cdt/.vnc/xstartup.sh && cat"]
    resources:
      requests:
        memory: "1.75Gi"
        cpu: "1"
      limits:
        memory: "1.75Gi"
        cpu: "1"
    volumeMounts:
    - name: settings-xml
      mountPath: /home/jenkins/.m2/settings.xml
      subPath: settings.xml
      readOnly: true
    - name: m2-repo
      mountPath: /home/jenkins/.m2/repository
    - name: volume-known-hosts
      mountPath: /home/jenkins/.ssh
  volumes:
  - name: settings-xml
    secret:
      secretName: m2-secret-dir
      items:
      - key: settings.xml
        path: settings.xml
  - name: m2-repo
    emptyDir: {}
  - name: volume-known-hosts
    configMap:
      name: known-hosts